brq.com.TFSDashboard.Web/Controllers/AcompanhamentoDemandasController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TFS_Dashboard.Repository.Context;
using TFS_Dashboard.Repository.Model;

namespace brq.com.TFSDashboard.Web.Controllers
{
    public class AcompanhamentoDemandasController : Controller
    {
        private DashboardDatabase db = new DashboardDatabase();

        // GET: AcompanhamentoDemandas
        public ActionResult Index()
        {
            return View(db.AcompanhamentoDemanda.ToList());
        }

        // GET: AcompanhamentoDemandas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcompanhamentoDemanda acompanhamentoDemanda = db.AcompanhamentoDemanda.Find(id);
            if (acompanhamentoDemanda == null)
            {
                return HttpNotFound();
            }
            return View(acompanhamentoDemanda);
        }

        // GET: AcompanhamentoDemandas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AcompanhamentoDemandas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Chave,Id_WorkItem,Dsc_Demanda,Esteira,Qtd_HorasTrabalhadas,Qtd_HorasFaturadas,Dt_Trabalho,Dt_Faturamento,Dsc_Observacao,Status,StatusTFS")] AcompanhamentoDemanda acompanhamentoDemanda)
        {
            if (ModelState.IsValid)
            {
                db.AcompanhamentoDemanda.Add(acompanhamentoDemanda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(acompanhamentoDemanda);
        }

        // GET: AcompanhamentoDemandas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcompanhamentoDemanda acompanhamentoDemanda = db.AcompanhamentoDemanda.Find(id);
            if (acompanhamentoDemanda == null)
            {
                return HttpNotFound();
            }
            return View(acompanhamentoDemanda);
        }

        // POST: AcompanhamentoDemandas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Chave,Id_WorkItem,Dsc_Demanda,Esteira,Qtd_HorasTrabalhadas,Qtd_HorasFaturadas,Dt_Trabalho,Dt_Faturamento,Dsc_Observacao,Status,StatusTFS")] AcompanhamentoDemanda acompanhamentoDemanda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(acompanhamentoDemanda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(acompanhamentoDemanda);
        }

        // GET: AcompanhamentoDemandas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcompanhamentoDemanda acompanhamentoDemanda = db.AcompanhamentoDemanda.Find(id);
            if (acompanhamentoDemanda == null)
            {
                return HttpNotFound();
            }
            return View(acompanhamentoDemanda);
        }

        // POST: AcompanhamentoDemandas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AcompanhamentoDemanda acompanhamentoDemanda = db.AcompanhamentoDemanda.Find(id);
            db.AcompanhamentoDemanda.Remove(acompanhamentoDemanda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

brq.com.TFSDashboard.Web/Controllers/ExpurgoSLAsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TFS_Dashboard.Repository.Context;
using TFS_Dashboard.Repository.Model;

namespace brq.com.TFSDashboard.Web.Controllers
{
    public class ExpurgoSLAController : Controller
    {
        private DashboardDatabase db = new DashboardDatabase();

        // GET: ExpurgoSLA
        public ActionResult Index()
        {
            return View(db.ExpurgoSLA.ToList());
        }

        // GET: ExpurgoSLA/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpurgoSLA expurgoSLA = db.ExpurgoSLA.Find(id);
            if (expurgoSLA == null)
            {
                return HttpNotFound();
            }
            return View(expurgoSLA);
        }

        // GET: ExpurgoSLA/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExpurgoSLA/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorkItemID,Dsc_ExpurgoSLAAnalise,Dsc_ExpurgoSLADimensionamento,Dsc_ExpurgoSLAEntrega,Dsc_RefazerDesenvolvimento")] ExpurgoSLA expurgoSLA)
        {
            if (ModelState.IsValid)
            {
                db.ExpurgoSLA.Add(expurgoSLA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(expurgoSLA);
        }

        // GET: ExpurgoSLA/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpurgoSLA expurgoSLA = db.ExpurgoSLA.Find(id);
            if (expurgoSLA == null)
            {
                return HttpNotFound();
            }
            return View(expurgoSLA);
        }

        // POST: ExpurgoSLA/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkItemID,Dsc_ExpurgoSLAAnalise,Dsc_ExpurgoSLADimensionamento,Dsc_ExpurgoSLAEntrega,Dsc_RefazerDesenvolvimento")] ExpurgoSLA expurgoSLA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expurgoSLA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expurgoSLA);
        }

        // GET: ExpurgoSLA/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpurgoSLA expurgoSLA = db.ExpurgoSLA.Find(id);
            if (expurgoSLA == null)
            {
                return HttpNotFound();
            }
            return View(expurgoSLA);
        }

        // POST: ExpurgoSLA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExpurgoSLA expurgoSLA = db.ExpurgoSLA.Find(id);
            db.ExpurgoSLA.Remove(expurgoSLA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

brq.com.TFSDashboard.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
   
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container col-md-12">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ONS Sustentação", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Acompanhamento de Demandas", "Index", "AcompanhamentoDemandas")</li>
                    <li>@Html.ActionLink("Expurgo SLA", "Index", "ExpurgoSLA")</li>
                    @*<li>@Html.ActionLink("Gerencial", "Index", "ExpurgoSLA")</li>*@
                </ul>
                @*<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>  Carlos Eduardo Alves Furtado<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Minhas Demandas", "Index", "ExpurgoSLA")</li>
                            <li><a href="#">Sair</a></li>
                        </ul>
                    </li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content col-md-12">
        @RenderBody()
    </div>
    <div class="col-md-12" style="padding-bottom: 2%;">

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>